/*
	by Nic Mulvaney
*/



module.exports = function(grunt) {

	// Folder settings
	var SOURCE = "lib/";

	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		// JSHint
		jshint: {
			files: [SOURCE+'score.js'],
			options: {
				laxcomma: true,
				boss: true,
				curly: true,
				eqeqeq: true,
				eqnull: true,
				es3: true,
				browser: true,
				smarttabs: true,
				"-W099": true, // Relax rules on mixed tabs and spaces
				globals: {
					jQuery: true
				}
			}
		},

		// Minified Javascript
		uglify: {
		  options: {
				banner: '/*! DO NOT EDIT THIS FILE */\n'+'/*! File Minified by grunt @ <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n',
				mangle: true
			},
			build: {
				src: SOURCE+'score.js',
				dest: SOURCE+'score.min.js'
			}		
		},
		// Watch files and build when they change
		watch: {
			js: {
				files: [SOURCE+'score.js'],
				tasks: ['uglify']
			}
		},
		notify_hooks: {
			options: {
				enabled: true,
				max_jshint_notifications: 2, 
				title: "Oops!" 
			}
		}

	});

	// Load grunt different tasks
	require('load-grunt-tasks')(grunt);
	grunt.task.run('notify_hooks');
	
	// Register grunt tasks
	grunt.registerTask('default', ['jshint', 'uglify', 'watch', 'notify:watch']);


};